server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sikshya_uat
    username: uat_user
    password: uat_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
